### ISSUE TITLE
Missing dependency resolution on the minimal package set RHEL6.9

### ISSUE THREAD

**Issue by jmazanek** [bmr-cymru/boom#12]
Hello,
When trying to run boom on the system with a minimal package set, I have hit the issue of missing python-argparse module.

    [root@rollback grub]# rpm -q python-boom
    python-boom-0.8-5.3.el6.noarch
    [root@rollback grub]# cat /etc/redhat-release 
    Red Hat Enterprise Linux Server release 6.9 (Santiago)
    [root@rollback grub]# boom profile list
    Traceback (most recent call last):
      File "/usr/bin/boom", line 4, in <module>
        from boom.command import main
      File "/usr/lib/python2.6/site-packages/boom/command.py", line 37, in <module>
        from argparse import ArgumentParser
    ImportError: No module named argparse

The argparse module is provided as a rpm package

    [root@rollback grub]# yum provides "*/argparse.py"
    Loaded plugins: product-id, search-disabled-repos, subscription-manager
    This system is not registered with an entitlement server. You can use subscription-manager to register.
    python-argparse-1.2.1-2.1.el6.noarch : Optparse inspired command line parser for Python
    Repo        : rhel-server
    Matched from:
    Filename    : /usr/lib/python2.6/site-packages/argparse.py

**Comment by bmr-cymru** [comment]
Thanks: I will add this requires to the in-tree RPM spec file, and let the RHEL maintainer know to add it in the next update.

**Comment by bmr-cymru** [comment]
This should be fixed in current master and builds from boom-0.8-5.5 onwards.
