### ISSUE TITLE
Similarity to clr-boot-manager?

### ISSUE THREAD

**Issue by Conan-Kudo** [bmr-cymru/boom#2]
This tool looks like it does the same thing as [clr-boot-manager](https://github.com/clearlinux/clr-boot-manager).

What makes this different/better than that tool?

**Comment by bmr-cymru** [comment]
There are a number of differences - in particular, we are not (yet) attempting to impose any kind of structure on distributions, beyond that required by the BootLoader Specification (for instance the location of kernels, their compiled-in build version or location in the file system). We also do not natively support any boot loader targets other than BLS: we made this decision based on the non-uniform UI support in different uEFI implementations and the fact that BLS supports a simple drop-in configuration style.

These differences likely come down to a difference in focus between the projects. Our initial interest is purely in simplifying the creation and management of boot loader entries for snapshots of system volumes on existing distributions. While we'd like to see some similar changes in the conventions used by distros to those documented on the `clr-boot-manager` site we're working to a strategy of fitting in with, and sitting alongside existing boot configurations for the time being.

Boom aims to be a small and simple tool that users can deploy right away on existing setups and that can immediately perform useful tasks without changes to existing packaging or installation requirements.

**Comment by Conan-Kudo** [comment]
@bmr-cymru Have you considered integrating aspects of boom into `clr-boot-manager`? It'd be nice if we were able to use that in Fedora for people who'd prefer something like this...

**Comment by bmr-cymru** [comment]
Not currently: they are written in different languages and have quite different focus as mentioned. It's possible in the future that the two projects could converge, but for now we are really focusing on the snapshot use cases and then more integration with other system components in Fedora and RHEL (e.g. snapshot creation with LVM2 or btrfs).

It's quite early days for the boom project still, and we're considering the possibility of rewriting some of the low level pieces in C (or another compiled language, e.g. rust) in the future once all the requirements and basics are fully settled. If we were to join up with another project to work on a combined tool that would likely be the time that that work would begin.
