### ISSUE TITLE
Integration with package managers

### ISSUE THREAD

**Issue by Klaas-** [bmr-cymru/boom#3]
Hi,
are there plans to integrate this with yum/dnf to roll back problematic updates for example? Or integrate with yum-plugin-fs-snapshot?

Greetings
Klaas

**Comment by bmr-cymru** [comment]
Nothing concrete as yet but it's certainly something that we intend to tackle - the [design document](https://github.com/bmr-cymru/snapshot-boot-docs) discuss this and as we move on to the higher-level components (supporting non-root file system snapshots and the snapshot manager) this is the kind of functionality we plan to include.

**Comment by Klaas-** [comment]
so I saw in the rhel8 htb presentation that this is being integrated to rollback rhel 7 -> rhel 8 upgrades with leapp. Is there any progress on using boom for a "normal" yum update rollback?

**Comment by bmr-cymru** [comment]
I'm going to close this as WONTFIX - we're getting ready to release `boom-1.0` now, and this functionality really belongs to the planned snapshot manager project that we'll be working on following the release. Thanks for reporting the issue though, and once we have a repo set up for the snapshot manager work I will re-open this issue against the new project.

**Comment by Klaas-** [comment]
@bmr-cymru please ping this issue when you do that :) looking forward to seeing the snapshot manager
